### PR TITLE
CO-2102_Return_generic_validation_error_were_no_Message_key_is_defined

### PR DESCRIPTION
**Pull request by ioigoume**
Change validationErrors rule name to a default error message

### CODE REVIEW

**Comment by boshrin** [comment]
Don't we need to do this in `StandardController::add` also?

**Comment by boshrin** [comment]
From today's meeting, the new language key will be something like "Please recheck %1$s"

**Comment by ioigoume** [comment]
@boshrin changed applied

**Comment by tomzeller** [comment]
Looks fine for the couple of models I tried.

Working through this as an example use case for the test framework.

Will try to automate other models.

**Pull request merged**
