### PR TITLE
Enrollment Flows page: enabling Pagination and Search

### PR DESCRIPTION
**Pull request by ioigoume**
Many communities requested both the pagination and search feature to be available in Enrollment Flows page since it was not convenient and efficient to fetch all of the available flows each time. Some of the communities have too many flows, one flow per class for example, which actually makes it impossible to admin with only a single page view.

### CODE REVIEW

**Comment by boshrin** [comment]
Related issues: [CO-1418](https://todos.internet2.edu/browse/CO-1418), [CO-821](https://todos.internet2.edu/browse/CO-821)

**Comment by spartanicus** [comment]
Hi, Ioannis - thanks for the work. 

On line 315 of app/Controller/CoEnrollmentFlowsController.php EnrollmentFlowStatusEnum doesn't exist in enum.php and should remain TemplateableStatusEnum. 

On line 318 we can avoid database-specific behavior by converting the query term to lower case (to match our indexes). Like so: ['LOWER(CoEnrollmentFlow.name) LIKE'].

Could you fix these items up?

**Comment by ioigoume** [comment]
Hi Arlen,
just pushed the fixes. 

Do you want from me to move the pull request under the develop branch?

**Comment by spartanicus** [comment]
Hi, Ioannis - thanks for the updates! Yes: if you could move the pull request to develop that would be great. (Hotfix branches are for bug-fixes rather than new feature development.)

**Comment by spartanicus** [comment]
Hi, Ioannis - sorry: I should have pointed out that you need to lower-case the search term as well (so you get a case-insensitive match). See lines 892-895 of CoPeopleController.php for an example.

Also - please make the entire legend clickable for opening the filter - take a look at View/CoPeople/search.inc - you'll find the JavaScript here has changed somewhat (we're in the midst of making all such filtering more consistent - and will be making further changes to make this whole area more generic and functional) - for now if you can modify this to behave more like on the CoPeople index that would be helpful so we can get this pulled.

**Comment by spartanicus** [comment]
Ioannis - I just pushed the basic group filtering up to develop. If you look at View/CoGroups/search.inc, you might have a better model to work your code against.

**Comment by ioigoume** [comment]
Hi Arlen,
made the changes you mentioned and pushed them. 
For the first one, i am sorry, it was silly from my side. As far as for the search.inc is concerned, i cross checked the View/CoGroups/search.inc, from the development branch, with the file i pushed before; and after making all analogous modifications, i merged the changes.
Please check if now everything is aligned with the requirements.

Before merging, please make a comment so that i can squash the commits.

**Comment by spartanicus** [comment]
Hi, Ioannis - this is great! Thanks for the changes - there are just three more small tweaks that will get everything aligned, and they're all in search.inc:

1. Please move id="top-search-toggle" (line 71) onto the <legend> (line 70) and remove the <a> tag that wraps the code starting at line 71.

2. Change the id on line 64 from "coGroupsSearch" to "coEnrollmentFlowSearch".

3. Simplify the JavaScript function starting on line 44 right down to the bare minimum - the default behavior no longer requires the use of cookies. The end result will look like this:

`$(function() {
    $( "#top-search-toggle").click(function() {
      $("#top-search-fields").toggle();
    });
  });`

Thanks again for the work!

**Comment by ioigoume** [comment]
Hi Arlen,
i pushed the changes requested. Also, i changed the indentation of search.inc so as to much the one from `View/CoGroups/search.inc`.

**Comment by spartanicus** [comment]
Thanks much, Ioannis - this all looks good. @boshrin: I'm good with accepting this pull request.  👍

**Comment by boshrin** [comment]
Let's do a quick review on the next dev call before I merge.

**Comment by skoranda** [comment]
First, apologies for the delay in getting this PR into the code base.

Second, to move this forward as quickly and easily as possible can you please close this PR, then rebase your code on the head of develop, and then submit a new PR against develop. Benn and Arlen are ready to approve that PR quickly when it arrives.

Again, thanks for the code, and sorry for this extra effort.

**Pull request closed without merging**
