### PR TITLE
CO-1630_No_Enrollment_Attribute_Default_Values_When_Using_Attribute_Enumerations

### PR DESCRIPTION
**Pull request by ioigoume**
vv_enums handle as json object.
Fetch attribute maps from DB if not enum available.

### CODE REVIEW

**Comment by spartanicus** [comment]
I see the Attribute Enumerations and can define a default value for an Enrollment Attribute of "Department (Organizational Identity)" - if this ticket aimed only to correct that, it appears to be working. However, what I don't see is the list of attributes (or the default value if set) in the enrollment flow. Is CO-1630 concerned only with the first issue or is it also concerned with the second?

**Comment by ioigoume** [comment]
@spartanicus could you please review. I rebased and tested on top of the develop branch

**Comment by spartanicus** [comment]
Hi, Ioannis - though I see the attribute enumeration in the Enrollment Flow configuration, I'm still only seeing a text input when the Enrollment Flow is run: 

`<div class="form-group">`
`      <label for="EnrolleeOrgIdentityOu">Org Dept</label>`
`      <input name="data[EnrolleeOrgIdentity][ou]" class="form-control" maxlength="128" type="text" id="EnrolleeOrgIdentityOu">`
`</div>`

I've got no errors behind the scenes and the cache is clear.

**Comment by boshrin** [comment]
Not sure I'm understanding the need for changes to AppModel.php...

**Pull request merged**
