### PR TITLE
Hotfix for CO-700 (when no T&C is present on an enrollment flow)

### PR DESCRIPTION
**Pull request by lionick**
Related to [PR-188](https://github.com/Internet2/comanage-registry/pull/188)
Fix a bug when no T&C is present on an enrollment flow

### CODE REVIEW

**Comment by spartanicus** [comment]
Hi, Nick - this does fix the fundamental issue that blocks an enrollment flow in a CO without Terms and Conditions. We note that the .modelbox div still appears:
image
which can be fixed with slightly more specific selectors for that (in this case "display: grid" is overriding the .hidden class).

What is likely better than hiding the div with CSS is to test in the view if Terms and Conditions are present at all, and only render the dummy box (for JavaScript construction) if they are. Is that achievable?

**Comment by lionick** [comment]
Hi Arlen, this is something we have discussed together and with Benn. The dummy box is needed, in case we have a modifiable membership and somenone can change COU at the enrollemnt flow. Because some COUs may not have T&C and others may have. CakePHP forms want to know all the fields when the page renders so we can't put the field for T&C adhoc, it must be there the moment the form loads. So we chose to have a dummy field instead of disabling security of the form. I was pretty sure that when I made the previous PR that .modelbox div didnt appear when was hidden (but it seems to be there now :P).  
I am not a CSS expert but i think in that case .hidden class loses its usability.  Maybe it would be better to add a specific css rule for that case?

**Comment by spartanicus** [comment]
Thanks, Nick - that makes sense (we do similar things elsewhere), and we can definitely just hide it with the following in co-responsive.css at around line 391 under the section  "/* PETITION ATTRIBUTES */" right below where display: grid is declared:

`body.petitionerAttributes .modelbox.hidden {
	display: none;
}`

**Comment by lionick** [comment]
Thanks Arlen, I have updated the PR and tested it ( It took me some time to bring the new updates from develop branch and configure it).

**Comment by spartanicus** [comment]
Looks great! Thanks, Nick :-)
I'll merge this now.

**Pull request merged**
