### PR TITLE
Fix person canvas sidebar search (CO-2766)

### PR DESCRIPTION
**Pull request by spartanicus**

### CODE REVIEW

**Comment by ioigoume** [comment]
@spartanicus the submit button does not render the inner Text correctly.

Screenshot from 2024-04-15 12-27-48

**Comment by ioigoume** [comment]
Hi @spartanicus ,
i am getting a warning while on debug mode. Can you please check the code change below :
 
 ```php
    $url['controller'] = $this->request->params['controller'];
    $url['action'] = $action;

    if(isset($this->data[$action])) {
      foreach($this->data[$action] as $key => $value) {
        // pass parameters
        if(is_int($key) && isset($value['pass'])) {
          array_push($url, filter_var($value['pass'], FILTER_SANITIZE_SPECIAL_CHARS));
        } else {
          foreach ($value as $knamed => $vnamed) {
            $url[$knamed] = filter_var($vnamed, FILTER_SANITIZE_SPECIAL_CHARS);
          }
        }
      }
    }
```

**Comment by spartanicus** [comment]
Good catch. Fixed and pushed.

**Comment by spartanicus** [comment]
We are backporting this PR to hotfix-4.3.x. This PR (targeted at develop) is being closed.

**Pull request closed without merging**
