### PR TITLE
Feature co 2392 part 2

### PR DESCRIPTION
**Pull request by rweber87**
Ticket: https://todos.internet2.edu/browse/CO-2392

Comments:
defaulting to blank option if none is specified when page loads.
cou_bug

### CODE REVIEW

**Comment by boshrin** [comment]
A couple of procedural notes...

1. The PR should go against `develop` if the ticket is flagged for the next feature release (in this case 4.1.0) or `hotfix-4.0.x' if flagged for the next bug fix release (in this case 4.0.3).
2. The PR should be rebased or otherwise cleaned up so "Files changed" only includes the changes you made and not whatever commits you happened to pick up. Let us know if you need help with this.

**Comment by rweber87** [comment]
Hi @boshrin! I initially made this PR from develop and then rebased that new branch off hotfix-4.0.x. Would it be cleaner if I just created a separate branch off the hotfix one with my change and created a PR to go into that hotfix branch?

**Comment by boshrin** [comment]
Oh yeah, that's just going to be an effort to clean up. I'd definitely create a local branch off hotfix and create a PR from there.

**Comment by rweber87** [comment]
Closing and creating new PR off hotfix branch

**Pull request closed without merging**
