### PR TITLE
[WIP] CO Group Search functionality

### PR DESCRIPTION
**Pull request by ioigoume**
Search Functionality for CO Groups - This is a functionality requested by EGI community and we have already encapsulated in COmanage 3.1.1 RCIAM version. Related tickets are CO-1496, CO-1418, CO-821

### CODE REVIEW

**Comment by spartanicus** [comment]
Hi, Ioannis - thanks again; this ticket conflicts with work I completed about a week ago but have yet to push on the develop branch. Thus far I have filtering on name, description, status, openness, type, and automatic vs. non-automatic groups.

image

We're also looking to filter "my groups" vs. "all groups".

**Comment by ioigoume** [comment]
Nice to hear that this functionality will be part of the next release. 
Nevertheless, from what i see the functionality refers to CoGroupMembers Model, while the functionality i am pushing refers to CoGroups. My understanding is that there needs to be consistency among the different Models that relate with each other. 
Do you want me to leave this open and make changes after you make your commit? Do you want me to remove the pull request?

**Comment by spartanicus** [comment]
Hi, Ioannis - the update applies to both views of the groups. The screenshot I sent is of the members, but the filtering appears on and applies to both. It probably makes sense to remove this pull request. Thanks!

**Comment by ioigoume** [comment]
Arlen, thank you for update . I am closing the pull request.

**Pull request closed without merging**
