### PR TITLE
 CO-929_Hierarchical_Representation_Of_Cous

### PR DESCRIPTION
**Pull request by lionick**
Add hierrachical representation of cous on my population list and CoPersonRole edit view dropdown list

### CODE REVIEW

**Comment by spartanicus** [comment]
This looks good to accept and works well. Approved for merge.

**Review by boshrin — COMMENTED** [review]
I'm a little confused by the threaded find in CoPersonRolesController, since it appears to be using Model calls and then re-finding on top of that. Shouldn't this be using [Tree Behavior](https://book.cakephp.org/2/en/core-libraries/behaviors/tree.html), which is what the Cou.php does?

I'm also not understanding the new `$parent` parameter passed into `Cou::childCousById()`, especially since the passed in parameter might then immediately be masked by a local variable of the same name.

What is the old and new expected behavior here?

**Comment by lionick** [comment]
Hi Benn, I'm glad you ask!
Before there was `$p['cous'] = $this->CoPersonRole->Cou->allCous($this->cur_co['Co']['id']);` which now is not sufficient as it returns all cous regardless level of cou and also returns only names . What we want now is to get the top level cous (not only theirs names but also ids). 
So firstly I thought to use **children** function which returns all top level cous BUT then I noticed that I cannot pass co_id so to have the right cous (pls correct me if i'm wrong).
So in order not to create another function at Cou.php I used **threaded** so I can have top level Cous.
If there is another sufficient way (e.g creating a new function) please share it.

Regarding the new argument at childCousById you are right is redundant, and forgotten after the refactoring. I will remove it and update the PR. Sorry for that.

**Comment by lionick** [comment]
Hi Benn, I have updated the PR.

**Comment by boshrin** [comment]
A couple of things.

First, the use of `$p['cous']` being set in `isAuthorized()` was confusing, because it is an old style of coding that we don't use anymore. I realize this was already there, but since you're working with this code, we should fix this to align with newer standards. Specifically, variables (like those used for select lists) should be set in `beforeRender()` and be prefixed `$vv_`. So the goal should be to add something like

```
$this->set('vv_available_cous', $this->CoPersonRole->Cou->childCousById(...));
```

to `CoPersonRole::beforeRender()` (and then remove the code that sets `$p['cous']` from `isAuthorized()`).

Second, I'm concerned about the changes to `Cou::childCousById()` since this function is also called from other places, and specifically `RoleComponent::couAdminFor()`. Have the changes been sufficiently tested to ensure `couAdminFor` (and the code that calls it) behaves as expected? It might be preferable to maintain the current behavior by default, but add a new flag to request the hierarchy in the name. eg:

```
public function childCousById($parentCouId, $includeParent=false, $includeHierarchy=false) {
  ...
}
```

**Comment by lionick** [comment]
Hi Benn, I will do the changes regarding $p['cous'].

As for Cou::childCousById() yes i can add a new flag. 
RoleComponent::couAdminFor() is called in two places one is at calculateCMRoles() and that affects the left menu under People where we can see the hierarchal representation of the cou (e.g My vo.example.eu / vo.example-sub-1.eu / vo.example-sub-2.eu Population). 
The second place is at RoleComponent:isCouAdminForCoPerson() where it only cares for the cou_id not the cou name. So it doesn't affect the functionality in that place.

**Comment by lionick** [comment]
Hi Benn, I've just updated the PR with the requested changes.

**Pull request merged**
