### PR TITLE
CO-1957_Improve_Login_Experience_/_Speed

### PR DESCRIPTION
**Pull request by ioigoume**
Added spinner for login.Removed login dependency from installation path.

### CODE REVIEW

**Comment by spartanicus** [comment]
See comments in https://todos.internet2.edu/browse/CO-1957 -- it may be worthwhile considering a slightly different approach due to the performance hit when loading a full html page rather than just doing a header redirect.

**Comment by spartanicus** [comment]
Hi, Ioannis - 

To simplify the existing page and remove external references, let's replace the spin.js code with simple CSS animation for loading. I'll follow along with this in the rest of the app. Please remove all Javascript references from index.php and add this style section to the <head>:

```
<style>
      @keyframes loading {
        0%   { opacity: 0.3; }
        30%  { opacity: 1.0; }
        100% { opacity: 0.3; }
      }
      #co-loading {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 160px;
        height: 100px;
        margin: -56px 0 0 -80px;
        padding: 0;
        font-size: 260px;
        line-height: 0;
        letter-spacing: -28px;
        color: #9FC6E2;
      }
      #co-loading span {
        animation: 1.2s linear infinite both loading;
      }
      #co-loading span:nth-child(2) {
        animation-delay: 0.2s;
      }
      #co-loading span:nth-child(3) {
        animation-delay: 0.4s;
      }
    </style>
```
Then in the body, we need only
`<div id="co-loading"><span>.</span><span>.</span><span>.</span></div>`

Since the page is much simpler, we can move the remaining php in the body to the php block above the <!DOCTYPE html> tag and remove all attributes from the <body> tag. 

Thanks!

**Comment by ioigoume** [comment]
Updated according to guidelines.

**Comment by boshrin** [comment]
Need to review UsersController changes wrt Match.

**Comment by boshrin** [comment]
I'm all in favor of getting rid of the `/registry` hardcoding, but for clarity I'd like to see that as a separate PR linked to CO-299.

**Comment by spartanicus** [comment]
This is good and checks out. This is ready for merge.

**Comment by spartanicus** [comment]
Ok here's the updated code:

The style should be:

`<style>
  @keyframes loading {
    0%   { opacity: 0.3; }
    30%  { opacity: 1.0; }
    100% { opacity: 0.3; }
  }
  #co-loading {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 160px;
    height: 100px;
    margin: -56px 0 0 -80px;
    padding: 0;
    line-height: 0;
    color: #9FC6E2;
    text-align: center;
  }
  #co-loading span {
    animation: 1.2s linear infinite both loading;
    background-color: #9FC6E2;
    display: inline-block;
    height: 28px;
    width: 28px;
    border-radius: 20px;
    margin: 0 2.5px;
  }
  #co-loading span:nth-child(2) {
    animation-delay: 0.2s;
  }
  #co-loading span:nth-child(3) {
    animation-delay: 0.4s;
  }
</style>`

and the div in the body is now

`<div` id="co-loading"><span></span><span></span><span></span></div>`

**Comment by ioigoume** [comment]
Hi @spartanicus ,
i made the change and rebased. Could you please review?

Ioannis

**Comment by spartanicus** [comment]
Thanks, Ioannis - this is great. The index.php piece of this is ready for merge. @boshrin I'll hand this off to you to review the UsersController.

**Pull request merged**
