### PR TITLE
CO-1544 Allow Terms and Conditions to be ordered

### PR DESCRIPTION
**Pull request by tomzeller**
https://bugs.internet2.edu/jira/projects/CO/issues/CO-1544

### CODE REVIEW

**Comment by boshrin** [comment]
Also this should be submitted against develop, not hotfix-*, as it's really an RFE not a bug.

**Comment by tomzeller** [comment]
Looks like (1) is because I copied [6a2655e178](https://github.com/Internet2/comanage-registry/commit/6a2655e178eda70dba49119d6a5d0eca7e282860#diff-a92f465c1299be94e1443ff52de3cbedR89).

Should I submit a PR for that class too ?

**Comment by tomzeller** [comment]
And app/View/CoTermsAndConditions/index.ctp:77 :

`<th><?php print $this->Paginator->sort('order', _txt('fd.tc.order')); ?></th>`

should be :

`<th><?php print $this->Paginator->sort('ordr', _txt('fd.tc.order')); ?></th>`

**Comment by tomzeller** [comment]
Benn, over to you for review.

**Comment by boshrin** [comment]
Re 6a2655e178, there's a lot of old code that shouldn't be copy/pasted :)

**Pull request merged**
